import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./celender.css"
import QueryProvider from "@/provider/reactQuery";
import { MuiMaterial } from "@/provider/muiMaterial";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Survay app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <MuiMaterial>
      <QueryProvider>
      <body className={"font-yekan "}>{children}</body>
      </QueryProvider>
      </MuiMaterial>
    </html>
  );
}
